#! /bin/bash

# configure cmake 
cmake -G "Unix Makefiles" \
	-DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_INSTALL_PREFIX="/usr/local" \
	-DWITH_TBB=ON \
	-DWITH_V4L=ON \
	-DINSTALL_C_EXAMPLES=OFF \
	-DINSTALL_PYTHON_EXAMPLES=OFF \
	-DBUILD_EXAMPLES=OFF \
	-DWITH_QT=ON \
	-DBUILD_FAT_JAVA_LIB=OFF \
	-DINSTALL_TO_MANGLED_PATHS=OFF \
	-DINSTALL_CREATE_DISTRIB=OFF \
	-DINSTALL_TESTS=ON \
	-DENABLE_FAST_MATH=OFF \
	-DWITH_IMAGEIO=ON \
	-DBUILD_SHARED_LIBS=OFF \
	-DWITH_OPENMP=ON \
	-DWITH_OPENGL=ON \
	-DWITH_GSTREAMER=ON \
	-DWITH_PNG=ON \
	-DWITH_JPEG=ON \
	-DWITH_TIFF=ON ..

# Assign all available cores
make -j`nproc`

# install
sudo make install
